title: "Frank's Ramblings"
author: "Frank Liu"
description: "Ramblings of a multilingual AI tech lead" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.
url: https://frankzliu.com

show_excerpts: false # set to true to show excerpts on the homepage

title: Frank's Ramblings
author:
  name: Frank Liu
description: > # this means to ignore newlines until "show_excerpts:"
  Ramblings of a multilingual AI tech lead.
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  #date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: frankzliu
    github: fzliu
    linkedin: fzliu

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

#theme: "minima"
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

kramdown:
  syntax_highlighter_opts:
    disable: true

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other

permalink: /:categories/:title

google_analytics: 1
